"""add_patient_archive_table

Revision ID: 57ba68ffb5ff
Revises: 5ca5eb64deda
Create Date: 2026-05-17 01:03:54.800577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '57ba68ffb5ff'
down_revision: Union[str, None] = '5ca5eb64deda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patientarchive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('patient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_patient_id', sa.Integer(), nullable=True),
    sa.Column('original_test_result_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patientarchive_session_code'), 'patientarchive', ['session_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patientarchive_session_code'), table_name='patientarchive')
    op.drop_table('patientarchive')
    # ### end Alembic commands ###
