"""add_exam_order_table

Revision ID: 5ca5eb64deda
Revises: 2a7b8c9d0e1f
Create Date: 2026-05-13 05:12:44.890753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import String as SA_String


# revision identifiers, used by Alembic.
revision: str = '5ca5eb64deda'
down_revision: Union[str, None] = '2a7b8c9d0e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patientregistry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age_display', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doctor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patientregistry_turno_id'), 'patientregistry', ['turno_id'], unique=True)
    op.create_table('examorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('session_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exam_types', SA_String(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('appsheet_row_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examorder_patient_id'), 'examorder', ['patient_id'], unique=False)
    op.create_index(op.f('ix_examorder_session_code'), 'examorder', ['session_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examorder_session_code'), table_name='examorder')
    op.drop_index(op.f('ix_examorder_patient_id'), table_name='examorder')
    op.drop_table('examorder')
    op.drop_index(op.f('ix_patientregistry_turno_id'), table_name='patientregistry')
    op.drop_table('patientregistry')
    # ### end Alembic commands ###
