"""Add sources_received to Patient model

Revision ID: 625785d8d616
Revises: 
Create Date: 2026-05-02 22:09:50.283391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '625785d8d616'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('session_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('waiting_room_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('patient', sa.Column('sources_received', postgresql.JSON(astext_type=Text()), nullable=True))
    op.create_index(op.f('ix_patient_session_code'), 'patient', ['session_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_session_code'), table_name='patient')
    op.drop_column('patient', 'sources_received')
    op.drop_column('patient', 'waiting_room_status')
    op.drop_column('patient', 'session_code')
    # ### end Alembic commands ###
