"""add_dataquarantine_table

Revision ID: 8ceb0d09a568
Revises: 7a1b2c3d4e5f
Create Date: 2026-05-20 08:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ceb0d09a568'
down_revision: Union[str, None] = '7a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataquarantine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('session_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataquarantine_status'), 'dataquarantine', ['status'], unique=False)
    op.create_index(op.f('ix_dataquarantine_received_at'), 'dataquarantine', ['received_at'], unique=False)
    op.create_index(op.f('ix_dataquarantine_session_code'), 'dataquarantine', ['session_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataquarantine_session_code'), table_name='dataquarantine')
    op.drop_index(op.f('ix_dataquarantine_received_at'), table_name='dataquarantine')
    op.drop_index(op.f('ix_dataquarantine_status'), table_name='dataquarantine')
    op.drop_table('dataquarantine')
    # ### end Alembic commands ###
